In [ ]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [ ]:
# 레이블 인코딩

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(items) # 내부적으로 번호에 데이터를 적용함 # 사용자에게 결과값을 주진 않는다.

labels = encoder.transform(items) # 인코딩 수행 labels 에서는 0,1,2,3 으로 들어가 있다.

In [ ]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [ ]:
print("인코딩 변환 값 : {}".format(labels))
print("인코딩 클래스 : {}".format(encoder.classes_)) # class 값 인출

인코딩 변환 값 : [0 1 4 5 3 3 2 2]
인코딩 클래스 : ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [ ]:
# 디코딩 : 컴퓨터가 알아들을 수 있는 정보에서 사람이 알아 볼 수 있는 정보로 변환
# 인코딩의 반대
encoder.inverse_transform([1,5,4,2,3,2,1,2,3,4,0])

array(['냉장고', '컴퓨터', '전자렌지', '믹서', '선풍기', '믹서', '냉장고', '믹서', '선풍기',
       '전자렌지', 'TV'], dtype='<U4')

In [ ]:
# 원-핫 인코딩
## 반드시 2차원 배열을 사용
## 원-핫 인코딩은 보통 Feature 에 사용되기 때문

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# 2차원 ndarray로 변환
items_arr = np.array(items).reshape(-1,1) #파이선 리스트를 넘파이 어레이 형식으로 변환
items_arr

array([['TV'],
       ['냉장고'],
       ['전자렌지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U4')

In [ ]:
encoder = OneHotEncoder()

ohe_labels = encoder.fit_transform(items_arr) #fit_transform() : fit(데이터를 입력)하고나서 transform(데이터를 변환)하는
ohe_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
print(ohe_labels)
# 1의 위치를 압축된 표현으로 확인

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0


In [ ]:
# 압축된 형식을 풀어서 표현
print(ohe_labels.toarray())

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [ ]:
# feature scaling

In [ ]:
# min-max scaling(정규화)

In [ ]:
import pandas as pd
movie_score = pd.DataFrame({
    "naver":[0, 2, 4, 6, 8],
    "netflix":[1, 2, 3, 4, 5]
})

movie_score

naver  netflix
0      0        1
1      2        2
2      4        3
3      6        4
4      8        5

In [ ]:
from sklearn.preprocessing import MinMaxScaler

mm_scaler = MinMaxScaler()
movie_score_scaled = mm_scaler.fit_transform(movie_score)
movie_score_scaled # 최소값 0으로 최대값 1로 세팅

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

In [ ]:
# standard scaling(표준화)
# 평균이 0,표준편차가 1이 되도록 변환

In [ ]:
data1 = np.array([100, 110, 120, 130, 140])
data2 = np.array([0, 1, 2, 3, 4])

In [ ]:
data1.mean(), data1.var(), data1.std()

(120.0, 200.0, 14.142135623730951)

In [ ]:
data2.mean(), data2.var(), data2.std()

(2.0, 2.0, 1.4142135623730951)

In [ ]:
from sklearn.preprocessing import StandardScaler

std_scaler1 = StandardScaler()
std_scaler2 = StandardScaler()

In [ ]:
data1_scaled = std_scaler1.fit_transform(data1.reshape(-1,1))
data2_scaled = std_scaler2.fit_transform(data2.reshape(-1,1))

In [ ]:
print(data1_scaled)
print()
print(data2_scaled)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
data1_scaled.mean(), data1_scaled.std()

(0.0, 0.9999999999999999)

In [ ]:
data2_scaled.mean(), data2_scaled.std() # 동일선상에 두고 데이터 비교 가능하도록

(0.0, 0.9999999999999999)